# Generated by Django 4.1 on 2024-10-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='water_Finished_goods_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='water_Finished_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('size', models.CharField(max_length=150, null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('date', models.DateField(auto_now=True)),
                ('stock', models.IntegerField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods_category')),
            ],
        ),
    ]
