# Generated by Django 4.1 on 2024-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0002_remove_water_finished_goods_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='damaged_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
