# Generated by Django 4.1 on 2024-10-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0003_damaged_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_finished_goods',
            name='total_stock',
            field=models.IntegerField(default=0),
        ),
    ]
