# Generated by Django 4.1 on 2024-10-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0005_damaged_good_category_damaged_goods_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damaged_good_category',
            name='category_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
