# Generated by Django 4.1 on 2024-10-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0006_alter_damaged_good_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damaged_goods',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
