# Generated by Django 4.1 on 2024-10-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0007_alter_damaged_goods_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='damaged_goods',
            name='total_stock',
            field=models.IntegerField(default=0),
        ),
    ]
