# Generated by Django 4.1 on 2024-10-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_app', '0004_water_finished_goods_total_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200, null=True)),
                ('license_number', models.CharField(max_length=200, null=True)),
                ('aadhaar_number', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=200, null=True)),
                ('route_distance', models.CharField(max_length=200, null=True)),
                ('route_startingdes', models.CharField(max_length=200, null=True)),
                ('route_endingdes', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200, null=True)),
                ('vehicle_nbr', models.CharField(max_length=200, null=True)),
                ('vehicle_img', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Route_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.driver')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.route')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='logistics_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.driver')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.route')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods')),
            ],
        ),
    ]
