# Generated by Django 4.1.2 on 2024-10-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route_endingdes',
            new_name='ending_point',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='route_startingdes',
            new_name='starting_point',
        ),
        migrations.AddField(
            model_name='route',
            name='total_distance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
