# Generated by Django 4.1.2 on 2024-10-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0002_rename_route_endingdes_route_ending_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_distance',
        ),
    ]
