# Generated by Django 4.1 on 2024-10-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_app', '0002_remove_rawmaterials_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterials_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=150, null=True, unique=True)),
                ('raw_materials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_app.rawmaterials')),
            ],
        ),
    ]
