# Generated by Django 4.1 on 2024-10-18 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0007_alter_damaged_goods_name'),
        ('inventory_app', '0006_finished_goods_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damaged_Goods_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('edamaged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='production_app.damaged_goods')),
            ],
        ),
    ]
