# Generated by Django 4.1 on 2024-10-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0007_alter_damaged_goods_name'),
        ('inventory_app', '0007_damaged_goods_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damaged_goods_stock',
            name='edamaged',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='production_app.damaged_goods'),
        ),
    ]
