# Generated by Django 4.1 on 2024-10-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0008_alter_damaged_goods_stock_edamaged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damaged_goods_stock',
            old_name='edamaged',
            new_name='damaged',
        ),
    ]
