# Generated by Django 5.0.6 on 2024-10-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0010_finished_goods_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_goods_request',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
