# Generated by Django 5.0.6 on 2024-10-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0012_finished_goods_request_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_goods_request',
            name='response',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='finished_goods_request',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
