# Generated by Django 5.0.6 on 2024-10-23 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0013_alter_finished_goods_request_response_and_more'),
        ('production_app', '0008_damaged_goods_total_stock'),
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_goods_request',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods_category'),
        ),
        migrations.AlterField(
            model_name='finished_goods_request',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.department'),
        ),
        migrations.AlterField(
            model_name='finished_goods_request',
            name='input_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finished_goods_request',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods'),
        ),
        migrations.AlterField(
            model_name='finished_goods_request',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='finished_goods_request',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
