# Generated by Django 5.0.6 on 2024-10-23 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0014_alter_finished_goods_request_category_and_more'),
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_goods_request',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.department'),
        ),
    ]
