# Generated by Django 4.1.2 on 2024-10-21 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Glenda_App', '0002_chatmessage'),
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_details', models.ManyToManyField(related_name='permissions', to='Glenda_App.menu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu Permission',
                'verbose_name_plural': 'Menu Permissions',
            },
        ),
    ]
