# Generated by Django 4.1.2 on 2024-10-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0002_menupermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_Name',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Product', 'Product'), ('Logistics', 'Logistics'), ('Production', 'Production'), ('R & D', 'R & D'), ('HR', 'HR')], max_length=20),
        ),
    ]
