# Generated by Django 4.1.2 on 2024-10-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0004_customuser_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_photo',
            new_name='image',
        ),
    ]
