# Generated by Django 4.1.2 on 2024-10-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0005_rename_profile_photo_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_Name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Product', 'Product'), ('Logistics', 'Logistics'), ('Production', 'Production'), ('R & D', 'R & D'), ('HR', 'HR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='designation',
            name='user_type',
            field=models.CharField(choices=[('chief ', 'CEO'), ('Manager', 'Manager'), ('Assistant Manager', 'Assistant Manager'), ('Executive', 'Executive')], max_length=20),
        ),
    ]
