# Generated by Django 4.1 on 2024-10-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterials',
            name='stock',
        ),
    ]
