# Generated by Django 4.1 on 2024-10-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0002_remove_rawmaterials_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterials',
            name='total_stock',
            field=models.IntegerField(default=0),
        ),
    ]
