# Generated by Django 4.1 on 2024-10-18 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_app', '0003_rawmaterials_total_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_phn', models.CharField(max_length=200, null=True)),
                ('vendor_district', models.CharField(max_length=150, null=True)),
                ('vendor_state', models.CharField(max_length=200, null=True)),
                ('vendor_country', models.CharField(max_length=150, null=True)),
                ('vendor_pincode', models.IntegerField(null=True)),
                ('pan_yes_or_no', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10, null=True)),
                ('vendor_PANNBR', models.CharField(blank=True, max_length=150, null=True)),
                ('vendor_Street', models.CharField(max_length=200, null=True)),
                ('vendor_Landmark', models.CharField(max_length=200, null=True)),
                ('vendor_Building', models.CharField(max_length=200, null=True)),
                ('vendor_listofpdcts', models.CharField(max_length=150, null=True)),
                ('materials', models.ManyToManyField(to='purchase_app.rawmaterials')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
